### ISSUE TITLE
Add a linter to make sure code is formatted properly.

### ISSUE THREAD

**Issue by Azbo400** [campDevs/DiscordBot#28] opened 2018-05-06 04:56 UTC
I think we should add an eslint or some similar linter to make sure that everyone contributing to the project uses the proper design and to insure that all the code is clean and good and formatted to our preferences (no semicolons, spaces, etc.)

**Comment by Azbo400** [comment] 2018-05-06 05:01
We should also add some file (contributing file, etc) that outlines the design style we want to prevent mistakes in pull requests.

**Comment by glynnw** [comment] 2018-05-06 06:39
This is a duplicate of #12 . Though I should probably edit the title of the issue to include linting.

**Closed** 2018-05-06 14:51 UTC
